### ISSUE TITLE
Tesitng MVP

### ISSUE THREAD

**Issue by espiautlewagon** [Andremegi/medical-app#14]
Here goes all the testing we have to do to ensure that the MVP is complete and working.

**Comment by espiautlewagon** [comment]
While the MVP is working, the model might be incorrect, as it returns that the patient have cancer, even if you answer **No** to all questions, and only be a 35 years old Male.

A set of combinatorics tests should be developed to automatically ask all possible answer combination, regardless of the age, to make sure that the answers aren't uniform. I'll dig into that.

**Comment by Andremegi** [comment]
Coucou , im not sure how to do that but its an option for sure . 
We have to keep in mind that at the moment the dataset target is completly imbalance , we should take care of that later on aswell . I'm not sure if it is that but the imbalance is very big...
Reminder : 
<img width="453" alt="LUNG_CANCER DISTRIBUTRION" src="https://github.com/user-attachments/assets/4c89df35-57f9-481e-ac03-ef605b32055a">
